# Generated by Django 3.2 on 2021-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_members_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
