# Generated by Django 3.2 on 2021-04-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_members_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id_t',
            field=models.CharField(default='12378', max_length=60, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(default='Pavel', max_length=110, verbose_name='ИМЯ'),
        ),
    ]
