# Generated by Django 3.2 on 2021-04-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210414_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id_s_list', models.CharField(max_length=560, verbose_name='Содержание')),
            ],
        ),
        migrations.CreateModel(
            name='Sendler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=60, verbose_name='Тема')),
                ('text', models.CharField(max_length=360, verbose_name='Содержание')),
                ('members_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.memberslist', verbose_name='Список для рассылки')),
            ],
        ),
    ]
