# Generated by Django 3.2 on 2021-04-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_memberslist_sendler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberslist',
            options={'verbose_name': 'Список для рассылки', 'verbose_name_plural': 'Списки для рассылки'},
        ),
        migrations.AlterModelOptions(
            name='sendler',
            options={'verbose_name': 'Рассылку', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='sendler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sendler_image/'),
        ),
        migrations.AddField(
            model_name='sendler',
            name='send_date',
            field=models.DateField(null=True),
        ),
    ]
