# Generated by Django 3.2 on 2021-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20210416_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendler',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
