# Generated by Django 3.2 on 2021-04-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_sendler_send_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendler',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='sendler',
            name='status',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='sendler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sendler_image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sendler',
            name='send_date',
            field=models.DateTimeField(null=True, verbose_name='Время отправки'),
        ),
    ]
