# Generated by Django 3.2 on 2021-04-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20210421_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='from_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
