# Generated by Django 3.2 on 2021-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_notifications_from_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='from_user_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
