# Generated by Django 3.2 on 2021-04-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_notifications_from_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_msg', models.CharField(max_length=4095)),
                ('to_user_msg', models.CharField(max_length=4095)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.members')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
