# Generated by Django 3.2 on 2021-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='from_user_msg',
            field=models.CharField(blank=True, max_length=4095, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='to_user_msg',
            field=models.CharField(blank=True, max_length=4095, null=True),
        ),
    ]
