# Generated by Django 3.2 on 2021-04-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20210424_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_state',
            field=models.CharField(blank=True, default='В начале', max_length=300, null=True, verbose_name='Состояние'),
        ),
    ]
