# Telegram Bot API Token
bot:
    token: 1823284420:AAHb4hmfmDpExwJRRSX8SVT3plip59EMk2s
    parse_mode: html

# Whether to skip previous updates or not
executor:
    skip_updates: true

# Visible commands
commands:
    start: Start conversation with me

test_payment_token:
    - 1744374395:TEST:7a2b10a6050bd4d443ae 