# Telegram Bot API Token
bot:
    token: 1735844036:AAFT3bUgJqzPTTMIHNqjB1TaGfHo26S-EKg
    parse_mode: markdownv2

# Whether to skip previous updates or not
executor:
    skip_updates: true

# Visible commands
commands:
    start: Start conversation with me

test_payment_token:
    - 381764678:TEST:24071